name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? Include stack/profile if relevant.
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: List exact steps and commands (including OS/stack/install script used).
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      placeholder: What you thought would happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour / logs
      placeholder: Include error output, screenshots, or logs if available.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: OS, stack slug/profile, devcontainer or local, and relevant versions.
