name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / problem
      description: What problem does this solve? Which stack/persona does it help?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behaviour, UX, or configuration change.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other ways to solve this, or why this approach is preferred.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, prior art, related stacks or MCP servers that might be impacted.
